### ISSUE TITLE
Is it possible to make them attached only to bottom side of screen while swiping? Like in real Tinder

### ISSUE THREAD

**Issue by NDruce** [flo-bit/svelte-swiper-cards#3]

**Comment by flo-bit** [comment]
To be honest I haven't used tinder in quite a while, so I'm not really sure what you mean by attached only to the bottom side, could you clarify that?

**Comment by NDruce** [comment]
Move cards only by that trajectory/path/line:

![image](https://github.com/flo-bit/svelte-swiper-cards/assets/33526036/ddb18e01-2a31-48e1-888d-b299a30b9fc0)

Not to any angle of screen (especially to top of screen, it should have option to be denied)

Examples:

![image](https://github.com/flo-bit/svelte-swiper-cards/assets/33526036/cc3d920f-9eb6-4509-a8d9-a711c3732081)

![image](https://github.com/flo-bit/svelte-swiper-cards/assets/33526036/a82b313a-fa40-4afd-a9ee-412ad2e08837)

They're bend over only to bottom (left/right, but attached/binded only to bottom side of screen)

**Comment by flo-bit** [comment]
i've added an anchor prop that should do basically that, set it to a high number (the higher the flatter the curve, should be at least 1000 i think) to get that behaviour
